% From MATLAB help: Neural Network Toolbox
%
% Script generated by NPRTOOL
function [] = nnetClassify(inputs, targets, test, testTargets, layers)
    % Get toolbox license - this is an issue with the 2012 version.
    % license('checkout', 'Neural_Network_Toolbox');
    
    % Our code - nnet functions require a different format.
%     inputs = transpose(inputs);
%     targets(targets == -1) = 0;
%     targets = transpose(targets);
%     test = transpose(test);
%     testTargets(testTargets == -1) = 0;
%     testTargets = transpose(testTargets);
    
    % Create a Pattern Recognition Network
    hiddenLayerSize = layers;
    net = patternnet(hiddenLayerSize);
    net.trainParam.showWindow=0;

    % Set up Division of Data for Training, Validation, Testing
    net.divideParam.trainRatio = 90/100;
    net.divideParam.valRatio = 5/100;
    net.divideParam.testRatio = 5/100;

    % Train the Network
    [net,tr] = train(net,inputs,targets);

    % Test the Network
    outputs = net(inputs);
    errors = gsubtract(targets,outputs);
    performance = perform(net,targets,outputs);

    % View the Network
    % view(net)

    % Plots
    % Uncomment these lines to enable various plots.
    %figure, plotperform(tr)
    %figure, plottrainstate(tr)
    figure, plotconfusion(targets,outputs)
    %figure, ploterrhist(errors)
    %figure, plotroc(targets, outputs);
end